# Generated by Django 4.2 on 2026-03-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("shop_name", models.CharField(default="regard.ru", max_length=100)),
                ("shop_item_id", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(max_length=500)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="RUB", max_length=3)),
                ("in_stock", models.BooleanField(default=True)),
                ("url", models.URLField(max_length=500)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                (
                    "extracted_mpn",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "normalized_name",
                    models.CharField(blank=True, db_index=True, max_length=500),
                ),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="shopitem",
            index=models.Index(
                fields=["shop_name", "last_seen"], name="prices_shop_shop_na_fec122_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopitem",
            index=models.Index(
                fields=["extracted_mpn"], name="prices_shop_extract_f1c4a8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shopitem",
            unique_together={("shop_name", "shop_item_id")},
        ),
    ]
