# Generated by Django 4.2 on 2026-03-13 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("components", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPUPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(auto_now_add=True)),
                ("in_stock", models.BooleanField(default=True)),
                ("url", models.URLField(max_length=500)),
                (
                    "cpu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="components.cpu",
                    ),
                ),
            ],
            options={
                "unique_together": {("cpu", "shop_name")},
            },
        ),
    ]
