# Generated by Django 4.2 on 2026-03-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Производитель"
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Нормализованное название",
                    ),
                ),
                (
                    "mpn",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="MPN",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=True, verbose_name="Из эталонного источника"
                    ),
                ),
                (
                    "series",
                    models.CharField(blank=True, max_length=100, verbose_name="Серия"),
                ),
                (
                    "microarchitecture",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Микроархитектура"
                    ),
                ),
                (
                    "core_family",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Семейство ядер"
                    ),
                ),
                ("socket", models.CharField(max_length=50, verbose_name="Сокет")),
                (
                    "core_count",
                    models.PositiveSmallIntegerField(verbose_name="Количество ядер"),
                ),
                (
                    "thread_count",
                    models.PositiveSmallIntegerField(verbose_name="Количество потоков"),
                ),
                (
                    "performance_core_clock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Базовая частота (ГГц)",
                    ),
                ),
                (
                    "performance_core_boost_clock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Макс. частота в бусте (ГГц)",
                    ),
                ),
                (
                    "l2_cache",
                    models.CharField(blank=True, max_length=20, verbose_name="Кэш L2"),
                ),
                (
                    "l3_cache",
                    models.CharField(blank=True, max_length=20, verbose_name="Кэш L3"),
                ),
                ("tdp", models.PositiveSmallIntegerField(verbose_name="TDP")),
                (
                    "integrated_graphics",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Встроенная графика"
                    ),
                ),
                (
                    "max_memory_support",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Макс. объем памяти (ГБ)"
                    ),
                ),
                (
                    "ecc_support",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Поддержка ECC"
                    ),
                ),
                (
                    "includes_cooler",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Кулер в комплекте"
                    ),
                ),
                (
                    "packaging",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Тип упаковки"
                    ),
                ),
                (
                    "lithography",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Техпроцесс"
                    ),
                ),
                (
                    "simultaneous_multithreading",
                    models.BooleanField(blank=True, null=True, verbose_name="SMT"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
