# Generated by Django 4.2 on 2026-03-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opendb_id",
                    models.CharField(
                        max_length=36, unique=True, verbose_name="OpenDB UUID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="Бренд"),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Нормализованное название",
                    ),
                ),
                (
                    "mpn",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Part Number (MPN)",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=True, verbose_name="Из эталонного источника"
                    ),
                ),
                (
                    "series",
                    models.CharField(blank=True, max_length=100, verbose_name="Серия"),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Вариант/модификация"
                    ),
                ),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год выпуска"
                    ),
                ),
                (
                    "part_numbers_json",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Список Part Numbers"
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Тип корпуса"
                    ),
                ),
                (
                    "supported_motherboard_form_factors",
                    models.TextField(
                        blank=True,
                        verbose_name="Поддерживаемые форм-факторы материнских плат",
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=100, verbose_name="Цвет"),
                ),
                (
                    "power_supply",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Блок питания (в комплекте)",
                    ),
                ),
                (
                    "side_panel",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Боковая панель"
                    ),
                ),
                (
                    "has_transparent_side_panel",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Прозрачная панель"
                    ),
                ),
                (
                    "front_panel_usb",
                    models.TextField(blank=True, verbose_name="USB на передней панели"),
                ),
                (
                    "max_video_card_length",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Макс. длина видеокарты (мм)",
                    ),
                ),
                (
                    "max_cpu_cooler_height",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Макс. высота кулера CPU (мм)",
                    ),
                ),
                (
                    "internal_3_5_bays",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Внутренних отсеков 3.5 дюйма",
                    ),
                ),
                (
                    "internal_2_5_bays",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Внутренних отсеков 2.5 дюйма",
                    ),
                ),
                (
                    "expansion_slots",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Слотов расширения"
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Габариты"
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Объем (литры)",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Вес (кг)",
                    ),
                ),
                (
                    "supported_power_supply_form_factors",
                    models.TextField(
                        blank=True, verbose_name="Поддерживаемые форм-факторы БП"
                    ),
                ),
            ],
            options={
                "verbose_name": "Корпус",
                "verbose_name_plural": "Корпуса",
            },
        ),
        migrations.CreateModel(
            name="CaseFan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opendb_id",
                    models.CharField(
                        max_length=36, unique=True, verbose_name="OpenDB UUID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="Бренд"),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Нормализованное название",
                    ),
                ),
                (
                    "mpn",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Part Number (MPN)",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=True, verbose_name="Из эталонного источника"
                    ),
                ),
                (
                    "series",
                    models.CharField(blank=True, max_length=100, verbose_name="Серия"),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Вариант/модификация"
                    ),
                ),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год выпуска"
                    ),
                ),
                (
                    "part_numbers_json",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Список Part Numbers"
                    ),
                ),
                (
                    "size",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Размер (мм)"
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=100, verbose_name="Цвет"),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Количество в упаковке"
                    ),
                ),
                (
                    "min_airflow",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Мин. воздушный поток (CFM)",
                    ),
                ),
                (
                    "max_airflow",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Макс. воздушный поток (CFM)",
                    ),
                ),
                (
                    "min_noise_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Мин. уровень шума (Дб)",
                    ),
                ),
                (
                    "max_noise_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Макс. уровень шума (Дб)",
                    ),
                ),
                ("pwm", models.BooleanField(blank=True, null=True, verbose_name="PWM")),
                (
                    "led",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Подсветка"
                    ),
                ),
                (
                    "connector",
                    models.CharField(blank=True, max_length=20, verbose_name="Разъем"),
                ),
                (
                    "controller",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Контроллер"
                    ),
                ),
                (
                    "static_pressure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Статическое давление",
                    ),
                ),
                (
                    "flow_direction",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Направление потока"
                    ),
                ),
            ],
            options={
                "verbose_name": "Корпусной вентилятор",
                "verbose_name_plural": "Корпусные вентиляторы",
            },
        ),
        migrations.CreateModel(
            name="CPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opendb_id",
                    models.CharField(
                        max_length=36, unique=True, verbose_name="OpenDB UUID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="Бренд"),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Нормализованное название",
                    ),
                ),
                (
                    "mpn",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Part Number (MPN)",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=True, verbose_name="Из эталонного источника"
                    ),
                ),
                (
                    "series",
                    models.CharField(blank=True, max_length=100, verbose_name="Серия"),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Вариант/модификация"
                    ),
                ),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год выпуска"
                    ),
                ),
                (
                    "part_numbers_json",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Список Part Numbers"
                    ),
                ),
                (
                    "cores_total",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Всего ядер"
                    ),
                ),
                (
                    "cores_performance",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Производительных ядер"
                    ),
                ),
                (
                    "threads",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Потоков"
                    ),
                ),
                (
                    "base_clock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Базовая частота (ГГц)",
                    ),
                ),
                (
                    "boost_clock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Макс. частота (ГГц)",
                    ),
                ),
                (
                    "l2_cache",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Кэш L2 (МБ)"
                    ),
                ),
                (
                    "l3_cache",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Кэш L3 (МБ)"
                    ),
                ),
                (
                    "integrated_graphics",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Встроенная графика"
                    ),
                ),
                (
                    "max_memory",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Макс. память (ГБ)"
                    ),
                ),
                (
                    "tdp",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="TDP (Вт)"
                    ),
                ),
                (
                    "ecc_support",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Поддержка ECC"
                    ),
                ),
                (
                    "includes_cooler",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="В комплекте кулер"
                    ),
                ),
                (
                    "packaging",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Тип упаковки"
                    ),
                ),
                (
                    "lithography",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Техпроцесс"
                    ),
                ),
                (
                    "smt",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Одновременная многопоточность",
                    ),
                ),
                (
                    "microarchitecture",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Микроархитектура"
                    ),
                ),
                (
                    "core_family",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Семейство ядер"
                    ),
                ),
                (
                    "socket",
                    models.CharField(blank=True, max_length=50, verbose_name="Сокет"),
                ),
                (
                    "memory_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Поддерживаемые типы памяти",
                    ),
                ),
            ],
            options={
                "verbose_name": "Процессор",
                "verbose_name_plural": "Процессоры",
            },
        ),
        migrations.CreateModel(
            name="CPUCooler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opendb_id",
                    models.CharField(
                        max_length=36, unique=True, verbose_name="OpenDB UUID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="Бренд"),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Нормализованное название",
                    ),
                ),
                (
                    "mpn",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Part Number (MPN)",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=True, verbose_name="Из эталонного источника"
                    ),
                ),
                (
                    "series",
                    models.CharField(blank=True, max_length=100, verbose_name="Серия"),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Вариант/модификация"
                    ),
                ),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год выпуска"
                    ),
                ),
                (
                    "part_numbers_json",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Список Part Numbers"
                    ),
                ),
                (
                    "min_fan_rpm",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Мин. обороты вентилятора"
                    ),
                ),
                (
                    "max_fan_rpm",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Макс. обороты вентилятора"
                    ),
                ),
                (
                    "min_noise_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Мин. уровень шума (Дб)",
                    ),
                ),
                (
                    "max_noise_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Макс. уровень шума (Дб)",
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=100, verbose_name="Цвет"),
                ),
                (
                    "height",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Высота (мм)"
                    ),
                ),
                (
                    "cpu_sockets",
                    models.TextField(blank=True, verbose_name="Совместимые сокеты"),
                ),
                (
                    "water_cooled",
                    models.BooleanField(
                        default=False, verbose_name="Водяное охлаждение"
                    ),
                ),
                (
                    "radiator_size",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Размер радиатора (мм)"
                    ),
                ),
                (
                    "fanless",
                    models.BooleanField(
                        default=False, verbose_name="Пассивное охлаждение"
                    ),
                ),
                (
                    "fan_size",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Размер вентилятора (мм)"
                    ),
                ),
                (
                    "fan_quantity",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Количество вентиляторов"
                    ),
                ),
            ],
            options={
                "verbose_name": "Кулер для процессора",
                "verbose_name_plural": "Кулеры для процессора",
            },
        ),
        migrations.CreateModel(
            name="GPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opendb_id",
                    models.CharField(
                        max_length=36, unique=True, verbose_name="OpenDB UUID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="Бренд"),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Нормализованное название",
                    ),
                ),
                (
                    "mpn",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Part Number (MPN)",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=True, verbose_name="Из эталонного источника"
                    ),
                ),
                (
                    "series",
                    models.CharField(blank=True, max_length=100, verbose_name="Серия"),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Вариант/модификация"
                    ),
                ),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год выпуска"
                    ),
                ),
                (
                    "part_numbers_json",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Список Part Numbers"
                    ),
                ),
                (
                    "chipset_manufacturer",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Производитель чипсета"
                    ),
                ),
                (
                    "chipset",
                    models.CharField(blank=True, max_length=100, verbose_name="Чипсет"),
                ),
                (
                    "memory",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Память (ГБ)"
                    ),
                ),
                (
                    "memory_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Тип памяти"
                    ),
                ),
                (
                    "core_base_clock",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Базовая частота ядра (МГц)"
                    ),
                ),
                (
                    "core_boost_clock",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Boost частота (МГц)"
                    ),
                ),
                (
                    "effective_memory_clock",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Эффективная частота памяти (МГц)",
                    ),
                ),
                (
                    "memory_bus",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Шина памяти (бит)"
                    ),
                ),
                (
                    "interface",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Интерфейс"
                    ),
                ),
                (
                    "frame_sync",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Технология синхронизации",
                    ),
                ),
                (
                    "length",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Длина (мм)"
                    ),
                ),
                (
                    "tdp",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="TDP (Вт)"
                    ),
                ),
                (
                    "case_expansion_slot_width",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Занимает слотов расширения"
                    ),
                ),
                (
                    "total_slot_width",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Общая ширина (слоты)"
                    ),
                ),
                (
                    "cooling",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Система охлаждения"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Цвет(а)"
                    ),
                ),
                (
                    "core_count",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Количество ядер CUDA / потоковых процессоров",
                    ),
                ),
                (
                    "power_connectors",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Разъемы питания"
                    ),
                ),
                (
                    "video_outputs",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Видеовыходы"
                    ),
                ),
            ],
            options={
                "verbose_name": "Видеокарта",
                "verbose_name_plural": "Видеокарты",
            },
        ),
        migrations.CreateModel(
            name="Motherboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opendb_id",
                    models.CharField(
                        max_length=36, unique=True, verbose_name="OpenDB UUID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="Бренд"),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Нормализованное название",
                    ),
                ),
                (
                    "mpn",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Part Number (MPN)",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=True, verbose_name="Из эталонного источника"
                    ),
                ),
                (
                    "series",
                    models.CharField(blank=True, max_length=100, verbose_name="Серия"),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Вариант/модификация"
                    ),
                ),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год выпуска"
                    ),
                ),
                (
                    "part_numbers_json",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Список Part Numbers"
                    ),
                ),
                (
                    "socket",
                    models.CharField(blank=True, max_length=50, verbose_name="Сокет"),
                ),
                (
                    "form_factor",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Форм-фактор"
                    ),
                ),
                (
                    "chipset",
                    models.CharField(blank=True, max_length=100, verbose_name="Чипсет"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Цвет(а)"
                    ),
                ),
                (
                    "memory_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Макс. объем памяти (ГБ)"
                    ),
                ),
                (
                    "memory_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Тип памяти"
                    ),
                ),
                (
                    "memory_slots",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Слотов памяти"
                    ),
                ),
                (
                    "sata_6_gb_s",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Порты SATA"
                    ),
                ),
                (
                    "m2_slots",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Слотов M.2"
                    ),
                ),
                (
                    "m2_slots_info",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Детали M.2 слотов"
                    ),
                ),
                (
                    "pcie_slots_info",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Детали PCIe слотов"
                    ),
                ),
                (
                    "raid_support",
                    models.BooleanField(default=False, verbose_name="Поддержка RAID"),
                ),
                (
                    "onboard_ethernet",
                    models.TextField(blank=True, verbose_name="Встроенный Ethernet"),
                ),
                (
                    "wireless",
                    models.CharField(blank=True, max_length=100, verbose_name="Wi-Fi"),
                ),
                (
                    "audio",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Аудиочип"
                    ),
                ),
                (
                    "back_panel_ports",
                    models.TextField(blank=True, verbose_name="Порты задней панели"),
                ),
                (
                    "power_connectors",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Разъемы питания"
                    ),
                ),
                (
                    "usb_headers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="USB заголовки"
                    ),
                ),
                (
                    "fan_headers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Заголовки вентиляторов"
                    ),
                ),
                (
                    "rgb_headers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="RGB заголовки"
                    ),
                ),
                (
                    "bios_features",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Особенности BIOS"
                    ),
                ),
            ],
            options={
                "verbose_name": "Материнская плата",
                "verbose_name_plural": "Материнские платы",
            },
        ),
        migrations.CreateModel(
            name="PowerSupply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opendb_id",
                    models.CharField(
                        max_length=36, unique=True, verbose_name="OpenDB UUID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="Бренд"),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Нормализованное название",
                    ),
                ),
                (
                    "mpn",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Part Number (MPN)",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=True, verbose_name="Из эталонного источника"
                    ),
                ),
                (
                    "series",
                    models.CharField(blank=True, max_length=100, verbose_name="Серия"),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Вариант/модификация"
                    ),
                ),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год выпуска"
                    ),
                ),
                (
                    "part_numbers_json",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Список Part Numbers"
                    ),
                ),
                (
                    "wattage",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Мощность (Вт)"
                    ),
                ),
                (
                    "form_factor",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Форм-фактор"
                    ),
                ),
                (
                    "efficiency_rating",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="Сертификат эффективности",
                    ),
                ),
                (
                    "modular",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Модульность"
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=100, verbose_name="Цвет"),
                ),
                (
                    "length",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Длина (мм)"
                    ),
                ),
                (
                    "fanless",
                    models.BooleanField(
                        default=False, verbose_name="Пассивное охлаждение"
                    ),
                ),
                (
                    "connectors",
                    models.JSONField(blank=True, default=dict, verbose_name="Разъемы"),
                ),
            ],
            options={
                "verbose_name": "Блок питания",
                "verbose_name_plural": "Блоки питания",
            },
        ),
        migrations.CreateModel(
            name="RAM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opendb_id",
                    models.CharField(
                        max_length=36, unique=True, verbose_name="OpenDB UUID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="Бренд"),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Нормализованное название",
                    ),
                ),
                (
                    "mpn",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Part Number (MPN)",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=True, verbose_name="Из эталонного источника"
                    ),
                ),
                (
                    "series",
                    models.CharField(blank=True, max_length=100, verbose_name="Серия"),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Вариант/модификация"
                    ),
                ),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год выпуска"
                    ),
                ),
                (
                    "part_numbers_json",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Список Part Numbers"
                    ),
                ),
                (
                    "modules_quantity",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Количество модулей в комплекте",
                    ),
                ),
                (
                    "capacity_per_module",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Объем одного модуля (ГБ)"
                    ),
                ),
                (
                    "total_capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Суммарный объем (ГБ)"
                    ),
                ),
                (
                    "speed",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Частота (МГц)"
                    ),
                ),
                (
                    "ram_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Тип памяти"
                    ),
                ),
                (
                    "form_factor",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Форм-фактор"
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=100, verbose_name="Цвет"),
                ),
                (
                    "cas_latency",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="CAS Latency"
                    ),
                ),
                (
                    "timings",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Тайминги"
                    ),
                ),
                (
                    "voltage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Напряжение (В)",
                    ),
                ),
                (
                    "ecc",
                    models.CharField(blank=True, max_length=20, verbose_name="ECC"),
                ),
                (
                    "registered",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Registered/Buffered"
                    ),
                ),
                (
                    "heat_spreader",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Теплораспределитель"
                    ),
                ),
                (
                    "rgb",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Подсветка"
                    ),
                ),
                (
                    "profile_support",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Поддерживаемые профили (XMP/EXPO)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оперативная память",
                "verbose_name_plural": "Оперативная память",
            },
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opendb_id",
                    models.CharField(
                        max_length=36, unique=True, verbose_name="OpenDB UUID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="Бренд"),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Нормализованное название",
                    ),
                ),
                (
                    "mpn",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Part Number (MPN)",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=True, verbose_name="Из эталонного источника"
                    ),
                ),
                (
                    "series",
                    models.CharField(blank=True, max_length=100, verbose_name="Серия"),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Вариант/модификация"
                    ),
                ),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год выпуска"
                    ),
                ),
                (
                    "part_numbers_json",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Список Part Numbers"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Объем (ГБ)"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Тип (SSD/HDD)"
                    ),
                ),
                (
                    "form_factor",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Форм-фактор"
                    ),
                ),
                (
                    "interface",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Интерфейс"
                    ),
                ),
                (
                    "nvme",
                    models.BooleanField(blank=True, null=True, verbose_name="NVMe"),
                ),
                (
                    "rpm",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Скорость вращения (RPM)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Накопитель",
                "verbose_name_plural": "Накопители",
            },
        ),
    ]
