# Generated by Django 4.2 on 2026-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0003_savedbuild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
